# Settings file automatically generated by admin_scripts test case
DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': ':memory:', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TEST_NAME': None, 'TIME_ZONE': 'UTC', 'TEST_COLLATION': None, 'OPTIONS': {}, 'HOST': '', 'USER': '', 'TEST_CHARSET': None, 'PASSWORD': '', 'PORT': ''}}
ROOT_URLCONF = 'slack.urls'
SECRET_KEY = '1w!xu5ubt=b4h3x&k+8buhemaf4lqflckrry58+_3zve8ah96z'
INSTALLED_APPS = [u'django.contrib.auth', u'django.contrib.contenttypes', u'admin_scripts']
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'slack': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'slack.utils.SlackHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'slack'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}
